// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CenteredIcon: typeof import('./src/components/icons/CenteredIcon.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpin: typeof import('naive-ui')['NSpin']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PwaNotification: typeof import('./src/components/PwaNotification.vue')['default']
    TheFooter: typeof import('./src/components/layout/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/layout/TheHeader.vue')['default']
  }
}

export { }
